### ISSUE TITLE
Saving and loading wizards showing up

### ISSUE THREAD

**Issue by AlmnoA** [ponyfan88/Craigs-Adventure#33]
Why are they there???

**Comment by ponyfan88** [comment]
what does this issue refer to?

**Comment by ponyfan88** [comment]
clarified the issue with @AlmnoA, if anyone could find steps to reproduce this issue that would be amazing (i cannot).

**Comment by XanderMooney** [comment]
added wontfix - hard to reproduce, saving isn't used often, and the webGL build does not include saving

**Comment by AlmnoA** [comment]
Thing manager on item prefabs were enemies.
